### ISSUE TITLE
algebraic effects

### ISSUE THREAD

**Issue by wishfoundry** [tonivade/purefun#57]
Hi!

really impressed by your work, especially the use of @FunctionalInterfaces is very inspiring.
I've been working a lot with heirarchical  context problems lately, and your code has been somewhat useful thought experiment

I was wondering, have you considered attempting to implement algebraic effects in this style?
https://overreacted.io/algebraic-effects-for-the-rest-of-us/
https://b-studios.de/scala-effekt/guides/getting-started.html
https://www.researchgate.net/publication/328511790_Effect_handlers_for_the_masses

**Comment by tonivade** [comment]
Hi @wishfoundry! Thank you for your kind words. I'm glad to hear that my code helps you. I started this project only to learn FP concepts, but it has grown to much to handle.

I don't know anything about algebraic effects and taking a quick look, it looks very interesting. I going to try to implement it if I found some time. Now I'm quite busy, but I promise to take a look.

**Comment by tonivade** [comment]
Hi again! 

I've been working last weekend in this pull request #58. Honestly, I'm don't know what I'm doing (I'm not a FP expert at all, and the papers are far from my understanding) and my backend is from OOP) but it seems it works, at least, the two basic [examples](https://b-studios.de/scala-effekt/guides/getting-started.html) of the documentation returns the same result :)

There are some parts without coverage, but I'm not sure how to test it. Do you know any other example, more complex, to test my development?

Kind regards!
